spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:dio2025
    username: dt2025
    password:
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create # validate | udate |create | crate-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      setting:
        trace: false
        web-allow-other: false
